language: node_js

dist: xenial

node_js:
  - 12

env:
  - IMG_QUALITY=30 COVER_QUALITY=70 ID_DIGITS=7

before_install:
  - sudo apt-get update -q
  - sudo apt-get install imagemagick -y --fix-missing

before_script:
  - npm i -g tuture@latest

script:
  - yarn
  - yarn download
  - yarn build:roadmaps
  - yarn build:tutorials
  - yarn clean
  - yarn algolia
  - yarn build
  - node script/deploy.js

cache: yarn
