language: node_js

dist: xenial

node_js:
  - 12

env:
  - IMG_QUALITY=30     # 文章中图片的 JPG 压缩质量
  - COVER_QUALITY=70   # 文章封面的 JPG 压缩质量
  - ID_DIGITS=7        # 文章 ID 位数（后期需要增加 ID 位数以避免碰撞）

before_install:
  - sudo apt-get update -q
  - sudo apt-get install imagemagick -y --fix-missing

before_script:
  - npm i -g tuture@latest

script:
  - yarn
  - yarn download
  - yarn build:roadmaps
  - yarn build:tutorials
  - yarn clean
  - yarn algolia
  - yarn build
  - node script/deploy.js

cache: yarn
