name: Deploy (Production)

on:
  push:
    branches:
    - production
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  deploy:
    runs-on: ubuntu-18.04

    # Only run this action in tuture-dev/hub
    if: github.repository == 'tuture-dev/hub'

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        ref: production

    - name: Update all submodules
      run: |
        git submodule foreach git pull origin master

    - name: Setup node environment
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install tuture globally
      run: |
        git clone --depth=1 https://github.com/tuture-dev/tuture.git
        cd tuture && yarn && yarn build && npm install -g

    - name: Cache imagemagick
      uses: actions/cache@v1
      id: imCache
      if: github.event_name != 'schedule'
      with:
        path: ImageMagick-7.*
        key: ${{ runner.OS }}-imagemagick
        restore_keys: ${{ runner.OS }}-imagemagick

    - name: Install imagemagick
      if: steps.imCache.outputs.cache-hit != 'true'
      run: |
        wget http://www.imagemagick.org/download/ImageMagick.tar.gz
        tar -xvf ImageMagick.tar.gz
        cd ImageMagick-7.*
        ./configure
        make -j8
        sudo make install
        sudo ldconfig /usr/local/lib

    - name: Cache node modules
      uses: actions/cache@v1
      if: github.event_name != 'schedule'
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Install npm dependencies and build hexo blog
      run: |
        yarn
        yarn buildTutorials
        yarn clean
        yarn algolia
        yarn build
      env:
        HEXO_ALGOLIA_INDEXING_KEY: ${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
