name: Deploy (Production)

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-18.04

    # Only run this action in tuture-dev/hub
    if: github.repository == 'tuture-dev/hub'

    steps:
      - name: Configuring git identity
        run: |
          git config --global user.email "1043269994@qq.com"
          git config --global user.name pftom
      - uses: actions/checkout@v2
        with:
          ref: production
          submodules: true

      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install tuture globally
        run: |
          npm install -g tuture
      - name: Cache node modules
        uses: actions/cache@v1
        if: github.event_name != 'schedule'
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - uses: sergioramos/yarn-actions/install@v6
        with:
          frozen-lockfile: true

      - name: Download repositories
        run: |
          yarn download

      - name: Build entire site
        run: |
          yarn build:roadmaps
          yarn build:tutorials
          yarn clean
          yarn algolia
          yarn build
        env:
          IMG_QUALITY: 30 # 文章中图片的 JPG 压缩质量
          COVER_QUALITY: 70 # 文章封面的 JPG 压缩质量
          ID_DIGITS: 7 # 文章 ID 位数（后期需要增加 ID 位数以避免碰撞）
          HEXO_ALGOLIA_INDEXING_KEY: ${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}

      - name: Deploy
        run: |
          git checkout -b $BRANCH_NAME
          node script/movePublicToRoot.js
          git add .
          git commit -m "Automatic deploy (`date`)"
        env:
          BRANCH_NAME: gh-pages
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: $BRANCH_NAME
          repository: $CODING_REPO
        env:
          CODING_REPO: ${{ secrets.CODING_REPO }}
          BRANCH_NAME: gh-pages
